-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local function hy3_dispatch(method, arg)
    return function()
        if hl.plugin and hl.plugin.hy3 and hl.plugin.hy3[method] then
            hl.dispatch(hl.plugin.hy3[method](arg))
        else
            if method == "movefocus" then
                local dir_map = { l = "left", r = "right", u = "up", d = "down" }
                hl.dispatch(hl.dsp.focus({ direction = dir_map[arg] or arg }))
            end
        end
    end
end


-- exec-once = sleep 2 && hyprctl reload


hl.config({
    debug = {
        suppress_errors = false,
    },
})

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

local num_screens = 0
local p = io.popen("cat /sys/class/drm/card*-*/status 2>/dev/null | grep -c '^connected'")
if p then
    local count_str = p:read("*a")
    p:close()
    local parsed = tonumber(count_str)
    if parsed and parsed > 0 then
        num_screens = parsed
    end
end
if num_screens == 0 then
    num_screens = 1
end

local ok, monitors = pcall(require, "monitors")
if not ok or type(monitors) ~= "table" then
    monitors = { mon1 = "", mon2 = "" }
    hl.monitor({
        output = "",
        mode = "preferred",
        position = "auto",
        scale = "auto",
    })
end
local mon1 = monitors.mon1
local mon2 = monitors.mon2

if mon2 and mon2 ~= "" and num_screens > 1 then
    -- Dual monitors: bind odd workspaces to mon1 (left) and even workspaces to mon2 (right)
    for i = 1, 10 do
        local target_mon = (i % 2 == 1) and mon1 or mon2
        hl.workspace({
            name = tostring(i),
            monitor = target_mon,
            default = (i == 1 or i == 2),
        })
    end
end

-- Force display on at startup (helps with black screen issues)


-- Xwayland config

-- unscale XWayland

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- toolkit-specific scale

hl.env("GDK_SCALE", 1)

hl.env("GDK_DPI_SCALE", 1)

hl.env("QT_SCALE_FACTOR", 1.3)

hl.env("XCURSOR_SIZE", 32)

-- For darktable

hl.env("GDK_BACKEND", "wayland")


--##################

--## MY PROGRAMS ###

--##################

-- Set programs that you use

local terminal = "kitty"

local fileManager = "pcmanfm"

local menu = "rofi -show drun"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:







--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("GRIMBLAST_HIDE_CURSOR", 1)

-- Fcitx5 (Wayland optimized)

hl.env("QT_IM_MODULE", "fcitx")

hl.env("XMODIFIERS", "@im=fcitx")

hl.env("SDL_IM_MODULE", "fcitx")

hl.env("GLFW_IM_MODULE", "fcitx")

hl.env("GTK_IM_MODULE", "")

-- Leaving this empty often helps in Wayland to use text-input-v3

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "hy3",
        col = {
            active_border = { colors = { "rgba(258ca8ff)", "rgba(25a846ff)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 0,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = false,
            --size = 3
            --passes = 1
            --vibrancy = 0.1696
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = false,
        --bezier = myBezier, 0.05, 0.9, 0.1, 1.05
        --animation = windows, 1, 7, myBezier
        --animation = windowsOut, 1, 7, default, popin 80%
        --animation = border, 1, 10, default
        --animation = borderangle, 1, 8, default
        --animation = fade, 1, 7, default
        --animation = workspaces, 1, 6, default
    },
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        preserve_split = true,
        -- You probably want this
        force_split = 2,
        permanent_direction_override = true,
    },
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = 1,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        background_color = "0x0",
        mouse_move_focuses_monitor = false,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
    },
})

-- hl.config({
--     plugin = {
--         hyprbars = {
--             bar_height = 30,
--             enabled = false,
--         },
--     },
-- })

hl.bind("CTRL + SUPER" .. " + " .. "T", hl.dsp.exec_cmd("~/repo/dotfiles/.i3_functions/toggle_windowtitles.sh"))

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "altgr-intl",
        repeat_delay = 200,
        repeat_rate = 50,
        follow_mouse = 2,
        float_switch_override_focus = 0,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.config({
    cursor = {
        no_warps = true,
    },
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind("SUPER" .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty"))

hl.bind("ALT" .. " + " .. "F4", hl.dsp.window.close())

hl.bind("SUPER" .. " + " .. "E", hl.dsp.exec_cmd("pcmanfm"))

hl.bind("SUPER + SHIFT" .. " + " .. "SPACE", hl.dsp.window.float())

hl.bind("SUPER" .. " + " .. "D", hl.dsp.exec_cmd("rofi -show drun"))

hl.bind("CTRL + ALT" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

hl.bind("SUPER" .. " + " .. "W", hl.dsp.exec_cmd("~/repo/dotfiles/.i3_functions/brave.sh"))

hl.bind("SUPER" .. " + " .. "P", hl.dsp.exec_cmd("~/repo/dotfiles/.zsh_functions/make_screenshot_wayland"))

hl.bind("SUPER + SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("~/repo/dotfiles/.zsh_functions/make_screenshot_latex"))

hl.bind("SUPER + SHIFT" .. " + " .. "K", hl.dsp.exec_cmd("hyprctl kill"))

hl.bind("SUPER + SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.dpms(\"off\")' && sleep 1 && hyprctl dispatch 'hl.dsp.dpms(\"on\")'"))

-- Move focus with mainMod + arrow keys

hl.bind("SUPER + right", hy3_dispatch("movefocus", "r"), { repeating = true })
hl.bind("SUPER + left", hy3_dispatch("movefocus", "l"), { repeating = true })
hl.bind("SUPER + up", hy3_dispatch("movefocus", "u"), { repeating = true })
hl.bind("SUPER + down", hy3_dispatch("movefocus", "d"), { repeating = true })
hl.bind("SUPER + H", hy3_dispatch("movefocus", "l"), { repeating = true })
hl.bind("SUPER + J", hy3_dispatch("movefocus", "d"), { repeating = true })
hl.bind("SUPER + K", hy3_dispatch("movefocus", "u"), { repeating = true })
hl.bind("SUPER + L", hy3_dispatch("movefocus", "r"), { repeating = true })

-- Switch workspaces with mainMod + [0-9] and Move active window to a workspace with mainMod + SHIFT + [0-9]

if num_screens > 1 and mon2 and mon2 ~= "" then
    -- Dual monitors workspace pairing (inspired by i3):
    -- Key 1 -> activates WS 2 on mon2, then WS 1 on mon1
    -- Key 2 -> activates WS 4 on mon2, then WS 3 on mon1
    -- Key 3 -> activates WS 6 on mon2, then WS 5 on mon1
    -- Key 4 -> activates WS 8 on mon2, then WS 7 on mon1
    -- Key 5 -> activates WS 10 on mon2, then WS 9 on mon1
    -- Key 6 -> activates WS 9 on mon1, then WS 10 on mon2
    local dual_pairs = {
        [1] = { left = 1, right = 2 },
        [2] = { left = 3, right = 4 },
        [3] = { left = 5, right = 6 },
        [4] = { left = 7, right = 8 },
        [5] = { left = 9, right = 10 },
        [6] = { left = 10, right = 9 },
    }

    for key, pair in pairs(dual_pairs) do
        -- Switch to workspace pair (focus right then left to leave focus on target)
        hl.bind("SUPER + " .. key, hl.dsp.exec_cmd(string.format(
            "hyprctl dispatch 'hl.dsp.focus({ workspace = %d })' && hyprctl dispatch 'hl.dsp.focus({ workspace = %d })'",
            pair.right, pair.left
        )))

        -- Move focused window to target workspace and switch workspace pair
        hl.bind("SUPER + SHIFT + " .. key, hl.dsp.exec_cmd(string.format(
            "hyprctl dispatch 'hl.dsp.window.move({ workspace = %d })' && hyprctl dispatch 'hl.dsp.focus({ workspace = %d })' && hyprctl dispatch 'hl.dsp.focus({ workspace = %d })'",
            pair.left, pair.right, pair.left
        )))
    end

    -- Additional direct bindings for workspaces 7, 8, 9, 0
    for i = 7, 10 do
        local key = (i == 10) and 0 or i
        hl.bind("SUPER + " .. key, hl.dsp.focus({ workspace = i }))
        hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
        hl.bind("SUPER + SHIFT + " .. key, hl.dsp.focus({ workspace = i }))
    end
else
    -- Single monitor: 1-to-1 mapping
    for i = 1, 10 do
        local key = (i == 10) and 0 or i
        hl.bind("SUPER + " .. key, hl.dsp.focus({ workspace = i }))
        hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
        hl.bind("SUPER + SHIFT + " .. key, hl.dsp.focus({ workspace = i }))
    end
end

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind("SUPER" .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind("SUPER" .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Move windows with keyboard

hl.bind("SUPER + CONTROL" .. " + " .. "H", hl.dsp.exec_cmd("~/repo/dotfiles/.hyprland_functions/move_window.sh l"), { repeating = true })

hl.bind("SUPER + CONTROL" .. " + " .. "L", hl.dsp.exec_cmd("~/repo/dotfiles/.hyprland_functions/move_window.sh r"), { repeating = true })

hl.bind("SUPER + CONTROL" .. " + " .. "K", hl.dsp.exec_cmd("~/repo/dotfiles/.hyprland_functions/move_window.sh u"), { repeating = true })

hl.bind("SUPER + CONTROL" .. " + " .. "J", hl.dsp.exec_cmd("~/repo/dotfiles/.hyprland_functions/move_window.sh d"), { repeating = true })

hl.bind("SUPER + CONTROL" .. " + " .. "left", hl.dsp.exec_cmd("~/repo/dotfiles/.hyprland_functions/move_window.sh l"), { repeating = true })

hl.bind("SUPER + CONTROL" .. " + " .. "right", hl.dsp.exec_cmd("~/repo/dotfiles/.hyprland_functions/move_window.sh r"), { repeating = true })

hl.bind("SUPER + CONTROL" .. " + " .. "up", hl.dsp.exec_cmd("~/repo/dotfiles/.hyprland_functions/move_window.sh u"), { repeating = true })

hl.bind("SUPER + CONTROL" .. " + " .. "down", hl.dsp.exec_cmd("~/repo/dotfiles/.hyprland_functions/move_window.sh d"), { repeating = true })

-- Split in horizontal orientation

hl.bind("SUPER + SHIFT + H", hy3_dispatch("makegroup", "h"))
hl.bind("SUPER + SHIFT + V", hy3_dispatch("makegroup", "v"))

-- Toggle fullscreen

hl.bind("SUPER" .. " + " .. "F", hl.dsp.window.fullscreen())

-- History

hl.bind("CONTROL + ALT" .. " + " .. "A", hl.dsp.exec_cmd("~/repo/dotfiles/.hyprland_functions/toggle_copyq.sh"))

-- Go to next/prev pdf

hl.bind("SUPER + SHIFT" .. " + " .. "right", hl.dsp.exec_cmd("~/repo/dotfiles/.hyprland_functions/next_pdf.sh next"))

hl.bind("SUPER + SHIFT" .. " + " .. "left", hl.dsp.exec_cmd("~/repo/dotfiles/.hyprland_functions/next_pdf.sh prev"))

-- Spotify

hl.bind("CTRL + ALT" .. " + " .. "period", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("CTRL + ALT" .. " + " .. "left", hl.dsp.exec_cmd("playerctl previous"))

hl.bind("CTRL + ALT" .. " + " .. "right", hl.dsp.exec_cmd("playerctl next"))

hl.bind("CTRL + ALT" .. " + " .. "up", hl.dsp.exec_cmd("pamixer -i 3 && pkill -RTMIN+10 waybar"))

hl.bind("CTRL + ALT" .. " + " .. "down", hl.dsp.exec_cmd("pamixer -d 3 && pkill -RTMIN+10 waybar"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 3 && pkill -RTMIN+10 waybar"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 3 && pkill -RTMIN+10 waybar"))

-- Brightness control

hl.bind("CTRL + SHIFT" .. " + " .. "up", hl.dsp.exec_cmd("brightnessctl set +5% && pkill -RTMIN+11 waybar"))

hl.bind("CTRL + SHIFT" .. " + " .. "down", hl.dsp.exec_cmd("brightnessctl set 5%- && pkill -RTMIN+11 waybar"))

-- Hangeul toggle

hl.bind("CONTROL + SHIFT" .. " + " .. "SPACE", hl.dsp.exec_cmd("~/.zsh_functions/toggle_hangeul"))

-- Ignore maximize requests from apps. You'll probably like this.

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Show screenshot

-- windowrulev2 = float, class:feh

-- windowrulev2 = center, class:feh

hl.window_rule({
    name  = "feh",
    match = {
        class = "feh",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name  = "imshow_rule",
    match = {
        title = ".*imshow_.*",
    },
    workspace = 4,
})

hl.window_rule({
    name  = "copyq",
    match = {
        class = "com.github.hluk.copyq",
    },
    float = true,
    size = "65% 65%",
    center = true,
    opacity = "0.87 override",
})

local mode_system = "(l) Lock| (e) Exit| (s) Suspend| (r) Reboot| (Shift+s) Poweroff"

hl.bind("SUPER" .. " + " .. "delete", hl.dsp.submap(mode_system))

hl.bind("SUPER" .. " + " .. "PRINT", hl.dsp.submap(mode_system))

hl.define_submap(mode_system, function()
    hl.bind("e", hl.dsp.exit())
    hl.bind("s", hl.dsp.exec_cmd("systemctl suspend"))
    hl.bind("SHIFT" .. " + " .. "s", hl.dsp.exec_cmd("systemctl poweroff -i"))
    hl.bind("h", hl.dsp.exec_cmd("systemctl hibernate"))
    hl.bind("r", hl.dsp.exec_cmd("systemctl reboot"))
    hl.bind("escape", hl.dsp.submap("reset"))
end)


hl.bind("SUPER" .. " + " .. "R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
    hl.bind("l", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 20 0"))
    hl.bind("h", hl.dsp.exec_cmd("hyprctl dispatch resizeactive -20 0"))
    hl.bind("k", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 -20"))
    hl.bind("j", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 20"))
    hl.bind("escape", hl.dsp.submap("reset"))
end)



-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("sleep 10 && pamixer --set-volume 50 && sleep 15 && pkill -RTMIN+10 waybar")
    -- hl.exec_cmd("sleep 1 && hyprctl dispatch 'hl.dsp.dpms(\"off\")' && sleep 1 && hyprctl dispatch 'hl.dsp.dpms(\"on\")'")
    hl.exec_cmd("waybar")
    hl.exec_cmd("insync start")
    hl.exec_cmd("copyq --start-server")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("~/repo/dotfiles/.hyprland_functions/pulseaudio_start_hook.sh")
    hl.exec_cmd("~/repo/dotfiles/.hyprland_functions/auto_split_imshow.sh")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_IM_MODULE GTK_IM_MODULE XMODIFIERS SDL_IM_MODULE GLFW_IM_MODULE")
end)
