#!/bin/sh
chrome() { 
   sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/google-chrome/'Local State'
   sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/google-chrome/Default/Preferences
   if [ "$#" -eq 0 ]; then
      nohup google-chrome-stable &> /dev/null & 
   else
      nohup google-chrome-stable $1 &> /dev/null & 
   fi
};
