#!/bin/env bash
lineofsink=`pactl list sinks | grep -ne $(pactl get-default-sink) | head -n1 | sed 's/:.*//'`
cardname=`pactl list sinks | sed -n "$(($lineofsink + 1))p" | cut -d ' ' -f2`
echo $cardname
