#!/bin/env zsh
cd ~/Pictures/ 

# Get a screenshot of the area selected by mouse
scrot -s


# Get path of this image
image_path=`ls -hrt -d $PWD/* | tail -n 1`

# Convert it to JPEG
#convert $image_path $image_path.jpg
#rm $image_path

# Put it in the clipboard
xclip -selection clipboard -t image/png -i $image_path

# Scan letters 
#ocr=`tesseract $image_path ocr -l kor && cat ocr.txt`
 #Remove spaces and substitute `_` with a space
#ocr=`echo $ocr | sed 's/ //g' | sed 's/_/ /g'`
 #Send it to clipboard 
#ocr=`echo $ocr | xclip`

# Display it onscreen
feh $(ls -hrt | tail -n 1)
