#!/bin/env zsh
name="main"

if [ "$#" -ne 0 ]; then
   name=${1%.*}
fi

latexmk -pdf -f "$name.tex" --output-directory=/tmp -halt-on-error && cp /tmp/"$name.pdf" .

process_exists=`hyprctl clients | grep "$name.pdf"`

if [ -z  $process_exists ]
then
   evince "$name.pdf" 2> /dev/null &
fi
