#!/bin/env zsh
name="main"

echo STARTING
if [ "$#" -ne 0 ]; then
   echo $1
   name=${1%.*}
   echo $name
fi

latexmk  -pdf -f "$name.tex" --output-directory=/tmp -halt-on-error && cp /tmp/"$name.pdf" .

process_exists=`ps -A | grep "evince"`
if [ -z  $process_exists ]
then
   evince "$name.pdf" 2> /dev/null &
fi
