#!/bin/env zsh

# Toggle between input methods
fcitx5-remote -t

# Get current state and notify (optional but helpful)
# 0: closed, 1: inactive, 2: active
state=$(fcitx5-remote)
if [[ $state == "2" ]]; then
    hyprctl notify 2 2000 "rgb(00ff00)" "Hangeul Enabled"
else
    hyprctl notify 2 2000 "rgb(ff0000)" "Hangeul Disabled"
fi
