#!/bin/env zsh

# Toggle Hangeul using fcitx5 with the original "kill" logic
program_name="fcitx5"

if pgrep -x $program_name >/dev/null
then
   # Kill the daemon as requested
   kill `pgrep $program_name`
else
   # Start the daemon
   /usr/bin/fcitx5 -d
fi
